#!/bin/bash

#aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'É em meio a dificuldade que se encontra a oportunidade'
aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'O êxito é ir de frustração a frustração sem perder a animação'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Mesmo que algo pareça difícil, nunca desista antes de tentar'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Você é o único que entende as suas dificuldades, por isso motive se a prosseguir'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Não é uma vida ruim, é apenas um dia ruim, lembre-se disso'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'A maior prova de que você pode fazer o impossível, é superar circunstâncias difíceis'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Que os dias bons se tornem rotina, e os ruins se tornem raros'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'É genial celebrar a vitória, contudo é mais significativo aprender com as lições da derrota'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Qualquer dificuldade pode ser ultrapassada, já que para todo problema há uma solução'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Já pensou que você já superou muitas dificuldades até aqui?'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Suas pequenas vitórias são todas as dificuldades superadas durante sua vida, tenha orgulho delas'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Cada dificuldade ultrapassada te faz mais forte'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Desistir não deve ser considerado, mesmo que as coisas não sejam fáceis'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'O êxito é a somatória dos pequenos esforços repetidos diariamente'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Para quem está iluminado, os dias de luz sempre retornam'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Conheci o pior das pessoas e o melhor de mim, passando por tempos difíceis'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Você não vai encontrar ninguém para sorrir por ti, então não deixe de sorrir'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Mesmo que nem todo dia seja bom, há algo de bom todo dia'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Em dias difíceis, lembre-se do que Deus já fez por ti. Recorde o que pode te oferecer esperança'
# aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sqs-message --message-body 'Da mesma forma que a felicidade não dura para sempre, a tristeza também não'